name: Consumer Workflow 1
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  call-reusable-workflow:
    uses: pappasam/reusable-workflow-demo/.github/workflows/reusable-workflow.yml@main
    with:
      file_name: "hello.txt"
